version: 2

sources:
  - name: dbcommodities_a6yp
    schema: public
    tables:
      - name: commodities
        description: "Tabela de commodities"
        columns:
          - name: Date
            description: "Data da cotação"
          - name: Close
            description: "Preço de fechamento"
          - name: simbolo
            description: "Símbolo da commodity"

  - name: dbcommodities_a6yp
    schema: public
    tables:
      - name: movimentacao_commodities
        description: "Tabela de movimentação de commodities"
        columns:
          - name: Date
            description: "Data da movimentação"
          - name: symbol
            description: "Símbolo da commodity"
          - name: action
            description: "Ação da movimentação"
          - name: quantity
            description: "Quantidade da movimentação"

            
